// SPDX-License-Identifier: Apache-2.0

//! Path 1: read a real header produced by `veritysetup`.

use std::{
    fs::File,
    io::{Read as _, Write as _},
    num::NonZero,
    process::Command,
};

use devmap_core::{BlockSize, Geometry};
use devmap_verity::header::{Algorithm, Constraint, HashType, Header, Salt};

#[test]
fn reads_a_header_written_by_veritysetup() {
    let directory = tempfile::tempdir().unwrap();
    let data_path = directory.path().join("data.img");
    let hash_path = directory.path().join("hash.img");

    // Create the protected data extent. `veritysetup` owns all writes to the
    // hash image, making the resulting header an independent compatibility
    // fixture rather than output produced by this crate.
    let mut data = File::create(&data_path).unwrap();
    data.write_all(&vec![0x5a; 8 * 4096]).unwrap();
    drop(data);

    let output = Command::new("veritysetup")
        .args([
            "format",
            "--format=1",
            "--data-block-size=4096",
            "--hash-block-size=4096",
            "--hash=sha256",
            "--salt=010203",
            "--uuid=5a5a5a5a-5a5a-5a5a-5a5a-5a5a5a5a5a5a",
        ])
        .arg(&data_path)
        .arg(&hash_path)
        .output()
        .expect("veritysetup must be installed for the header compatibility test");
    assert!(
        output.status.success(),
        "veritysetup format failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    // Our pathway only opens the completed hash image for reading and decodes
    // the standard record generated by the external implementation.
    let mut hash = File::open(hash_path).unwrap();
    let mut record = [0; 512];
    hash.read_exact(&mut record).unwrap();
    let actual = Header::decode(record).unwrap();

    let expected = Header {
        uuid: [0x5a; 16],
        hash_type: HashType::Normal,
        algorithm: Algorithm::Sha256,
        salt: Salt::new(&[1, 2, 3]).unwrap(),
        data: Geometry {
            size: BlockSize::<Constraint>::default(),
            count: NonZero::new(8).unwrap(),
        },
        hash: BlockSize::default(),
    };

    assert_eq!(actual, expected);
}
